### ISSUE TITLE
The run_litmus_test job should have a consistent name 

### ISSUE THREAD

**Issue by ksatchit** [openebs/litmus#36]
The run_litmus_test.yaml - which is the main deployment corresponding to each automated test under "tests" folder should use a common job name:

```
apiVersion: v1
kind: Job
metadata:
  name: litmus
  namespace: litmus 
```

This is useful for the executor framework which tracks the job lifecycle by the name.

**Comment by AmitKumarDas** [comment]
@ksatchit I believe labels are the ones which should be to track. Name should be unique in 'litmus' namespace.

**Comment by ksatchit** [comment]
@AmitKumarDas , agreed. Thanks for the suggestion. 

We are now following the policy that the litmus job labels are "unique" within the litmus namespace. The job labels are derived from the test-name/test-intent. Refer the chaos jobs for example: https://github.com/openebs/litmus/tree/master/apps/percona/chaos 

```
---
apiVersion: batch/v1
kind: Job
metadata:
  generateName: openebs-volume-replica-failure- 
  namespace: litmus 
spec:
  template:
    metadata:
      labels:
        name: openebs-volume-replica-failure 
```

Also, note that the job name (metadata.name) are also unique due to the use of generateName API.
